version: "3"

services:

  mysql:
    image: mysql:8.0.30-debian
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: routes
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.docker/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql" ,"-h", "mysql", "-P", "3306", "-u", "root", "-e", "SELECT 1", "cache"]
      interval: 5s
      timeout: 5s
      retries: 20
      
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
      
